sudo: required
services:
  - docker

before_install:
  - docker build -t kartishrakhunde/docker-react -f Dockerfile.dev .

script:
  - docker run CI=true kartishrakhunde/docker-react npm run test -- --coverage